import type { Metadata } from 'next';
import { rubikDirt, merriweatherSans } from './fonts';
import { ThemeProvider } from 'next-themes';
import '@/styles/globals.css';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };
export const metadata: Metadata = {
  metadataBase: new URL('https://convergens.zac.coffee'), // your prod URL
  title: {
    default: 'ConvergENS',
    template: '%s | ConvergENS',
  },
  description: 'ConvergENS – associations, events & articles.',
  icons: {
    icon: '/favicon.ico',
    apple: '/apple-touch-icon.png',
  },
  openGraph: {
    type: 'website',
    title: 'ConvergENS',
    siteName: 'ConvergENS',
  },
  alternates: {
    canonical: '/',
    languages: { en: '/en', fr: '/fr' },
  },
  robots: { index: true, follow: true },
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body
        className={`${merriweatherSans.variable} ${rubikDirt.variable} antialiased`}
      >
        <ThemeProvider attribute="class" enableSystem defaultTheme="system">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
